#!/usr/bin/env php
<?php
$path1 = __DIR__ . '/vendor/autoload.php';
$path2 = __DIR__ . '/../../autoload.php';
if (file_exists($path1)) {
  require $path1;
} else {
  require $path2;
}

$doc = <<<DOC
Generate diff

Usage:
  gendiff (-h | --help)
  gendiff [--format <fmt>] <firstFile> <secondFile>

Options:
  -h --help         Show this screen.
  --format <fmt>    Report format [default: pretty]

DOC;

$args = Docopt::handle($doc, array('version'=>'Generate diff 1.0'));
foreach ($args as $k=>$v) {
  echo $k.': '.json_encode($v).PHP_EOL; 
}    
